package info.qbnet.cubecmd;

import info.qbnet.jtvision.util.PaletteRole;
import info.qbnet.jtvision.util.TPalette;

import java.util.EnumMap;

/**
 * CubeCmd root palette extracted from DN CColor table (DNAPP.PAS).
 * Names come from Turbo Vision roles where known; DN editor/file-info/file-find
 * ranges are labeled explicitly; additional high slots were mapped from DN units (DBLWND/DBVIEW/HELPFILE/FIXER/UNIWIN) where possible.
 */
public final class CubeCmdPalette {
    private CubeCmdPalette() {}

    public enum AppColorSlot implements PaletteRole {
        BACKGROUND,
        MENU_NORMAL_TEXT,
        MENU_DISABLED_TEXT,
        MENU_SHORTCUT_TEXT,
        MENU_NORMAL_SELECTION,
        MENU_DISABLED_SELECTION,
        MENU_SHORTCUT_SELECTION,
        BLUE_WINDOW_FRAME_PASSIVE,
        BLUE_WINDOW_FRAME_ACTIVE,
        BLUE_WINDOW_FRAME_ICON,
        BLUE_WINDOW_SCROLLBAR_PAGE,
        BLUE_WINDOW_SCROLLBAR_CONTROLS,
        BLUE_WINDOW_SCROLLER_NORMAL,
        BLUE_WINDOW_SCROLLER_SELECTED,
        BLUE_WINDOW_RESERVED,
        CYAN_WINDOW_FRAME_PASSIVE,
        CYAN_WINDOW_FRAME_ACTIVE,
        CYAN_WINDOW_FRAME_ICON,
        CYAN_WINDOW_SCROLLBAR_PAGE,
        CYAN_WINDOW_SCROLLBAR_CONTROLS,
        CYAN_WINDOW_SCROLLER_NORMAL,
        CYAN_WINDOW_SCROLLER_SELECTED,
        CYAN_WINDOW_RESERVED,
        GRAY_WINDOW_FRAME_PASSIVE,
        GRAY_WINDOW_FRAME_ACTIVE,
        GRAY_WINDOW_FRAME_ICON,
        GRAY_WINDOW_SCROLLBAR_PAGE,
        GRAY_WINDOW_SCROLLBAR_CONTROLS,
        GRAY_WINDOW_SCROLLER_NORMAL,
        GRAY_WINDOW_SCROLLER_SELECTED,
        GRAY_WINDOW_RESERVED,
        GRAY_DIALOG_FRAME_PASSIVE,
        GRAY_DIALOG_FRAME_ACTIVE,
        GRAY_DIALOG_FRAME_ICON,
        GRAY_DIALOG_SCROLLBAR_PAGE,
        GRAY_DIALOG_SCROLLBAR_CONTROLS,
        GRAY_DIALOG_STATIC_TEXT,
        GRAY_DIALOG_LABEL_NORMAL,
        GRAY_DIALOG_LABEL_SELECTED,
        GRAY_DIALOG_LABEL_SHORTCUT,
        GRAY_DIALOG_BUTTON_NORMAL,
        GRAY_DIALOG_BUTTON_DEFAULT,
        GRAY_DIALOG_BUTTON_SELECTED,
        GRAY_DIALOG_BUTTON_DISABLED,
        GRAY_DIALOG_BUTTON_SHORTCUT,
        GRAY_DIALOG_BUTTON_SHADOW,
        GRAY_DIALOG_CLUSTER_NORMAL,
        GRAY_DIALOG_CLUSTER_SELECTED,
        GRAY_DIALOG_CLUSTER_SHORTCUT,
        GRAY_DIALOG_INPUT_LINE_NORMAL_TEXT,
        GRAY_DIALOG_INPUT_LINE_SELECTED_TEXT,
        GRAY_DIALOG_INPUT_LINE_ARROWS,
        GRAY_DIALOG_HISTORY_ARROW,
        GRAY_DIALOG_HISTORY_SIDES,
        GRAY_DIALOG_HISTORY_WINDOW_PAGE,
        GRAY_DIALOG_HISTORY_WINDOW_CONTROLS,
        GRAY_DIALOG_LIST_VIEWER_NORMAL,
        GRAY_DIALOG_LIST_VIEWER_FOCUSED,
        GRAY_DIALOG_LIST_VIEWER_SELECTED,
        GRAY_DIALOG_LIST_VIEWER_DIVIDER,
        GRAY_DIALOG_INFO_PANE,
        GRAY_DIALOG_CLUSTER_DISABLED,
        GRAY_DIALOG_RESERVED,
        EDITOR_COLOR_064,
        EDITOR_COLOR_065,
        EDITOR_COLOR_066,
        EDITOR_COLOR_067,
        EDITOR_COLOR_068,
        EDITOR_COLOR_069,
        EDITOR_COLOR_070,
        EDITOR_COLOR_071,
        EDITOR_COLOR_072,
        EDITOR_COLOR_073,
        EDITOR_COLOR_074,
        EDITOR_COLOR_075,
        EDITOR_COLOR_076,
        EDITOR_COLOR_077,
        EDITOR_COLOR_078,
        EDITOR_COLOR_079,
        BLUE_DIALOG_CLUSTER_SELECTED,
        BLUE_DIALOG_CLUSTER_SHORTCUT,
        BLUE_DIALOG_INPUT_LINE_NORMAL_TEXT,
        BLUE_DIALOG_INPUT_LINE_SELECTED_TEXT,
        BLUE_DIALOG_INPUT_LINE_ARROWS,
        BLUE_DIALOG_HISTORY_ARROW,
        BLUE_DIALOG_HISTORY_SIDES,
        BLUE_DIALOG_HISTORY_WINDOW_PAGE,
        BLUE_DIALOG_HISTORY_WINDOW_CONTROLS,
        BLUE_DIALOG_LIST_VIEWER_NORMAL,
        BLUE_DIALOG_LIST_VIEWER_FOCUSED,
        BLUE_DIALOG_LIST_VIEWER_SELECTED,
        BLUE_DIALOG_LIST_VIEWER_DIVIDER,
        BLUE_DIALOG_INFO_PANE,
        BLUE_DIALOG_CLUSTER_DISABLED,
        BLUE_DIALOG_RESERVED,
        CYAN_DIALOG_FRAME_PASSIVE,
        CYAN_DIALOG_FRAME_ACTIVE,
        CYAN_DIALOG_FRAME_ICON,
        CYAN_DIALOG_SCROLLBAR_PAGE,
        CYAN_DIALOG_SCROLLBAR_CONTROLS,
        CYAN_DIALOG_STATIC_TEXT,
        CYAN_DIALOG_LABEL_NORMAL,
        CYAN_DIALOG_LABEL_SELECTED,
        CYAN_DIALOG_LABEL_SHORTCUT,
        CYAN_DIALOG_BUTTON_NORMAL,
        CYAN_DIALOG_BUTTON_DEFAULT,
        CYAN_DIALOG_BUTTON_SELECTED,
        CYAN_DIALOG_BUTTON_DISABLED,
        CYAN_DIALOG_BUTTON_SHORTCUT,
        CYAN_DIALOG_BUTTON_SHADOW,
        CYAN_DIALOG_CLUSTER_NORMAL,
        CYAN_DIALOG_CLUSTER_SELECTED,
        CYAN_DIALOG_CLUSTER_SHORTCUT,
        CYAN_DIALOG_INPUT_LINE_NORMAL_TEXT,
        CYAN_DIALOG_INPUT_LINE_SELECTED_TEXT,
        CYAN_DIALOG_INPUT_LINE_ARROWS,
        CYAN_DIALOG_HISTORY_ARROW,
        CYAN_DIALOG_HISTORY_SIDES,
        FILE_INFO_COLOR_119,
        FILE_INFO_COLOR_120,
        FILE_INFO_COLOR_121,
        FILE_INFO_COLOR_122,
        FILE_INFO_COLOR_123,
        FILE_INFO_COLOR_124,
        FILE_INFO_COLOR_125,
        FILE_FIND_COLOR_126,
        FILE_FIND_COLOR_127,
        FILE_FIND_COLOR_128,
        FILE_FIND_COLOR_129,
        FILE_FIND_COLOR_130,
        FILE_FIND_COLOR_131,
        FILE_FIND_COLOR_132,
        FILE_FIND_COLOR_133,
        FILE_FIND_COLOR_134,
        FILE_FIND_COLOR_135,
        FILE_FIND_COLOR_136,
        FILE_FIND_COLOR_137,
        FILE_FIND_COLOR_138,
        DN_EXTRA_139,
        HELP_WINDOW_SLOT_002,
        HELP_WINDOW_SLOT_003,
        DN_EXTRA_142,
        DN_EXTRA_143,
        HELP_WINDOW_SLOT_006,
        HELP_WINDOW_SLOT_007,
        HELP_WINDOW_SLOT_008,
        FIXER_WINDOW_SLOT_002,
        FIXER_WINDOW_SLOT_003,
        FIXER_WINDOW_SLOT_004,
        FIXER_WINDOW_SLOT_005,
        FIXER_WINDOW_SLOT_006,
        FIXER_WINDOW_SLOT_007,
        FIXER_WINDOW_SLOT_001,
        FIXER_WINDOW_SLOT_008,
        FIXER_WINDOW_SLOT_009,
        FIXER_WINDOW_SLOT_010,
        FIXER_WINDOW_SLOT_011,
        FIXER_WINDOW_SLOT_012,
        FIXER_WINDOW_SLOT_013,
        FIXER_WINDOW_SLOT_014,
        FIXER_WINDOW_SLOT_015,
        FIXER_WINDOW_SLOT_016,
        HELP_WINDOW_SLOT_009,
        UNI_WINDOW_SLOT_016,
        DOUBLE_WINDOW_SLOT_032,
        DB_WINDOW_SLOT_001,
        DB_WINDOW_SLOT_002,
        DB_WINDOW_SLOT_003,
        DB_WINDOW_SLOT_004,
        DB_WINDOW_SLOT_005,
        DB_WINDOW_SLOT_006,
        DOUBLE_WINDOW_SLOT_033,
        DOUBLE_WINDOW_SLOT_034,
        DOUBLE_WINDOW_SLOT_035,
        DOUBLE_WINDOW_SLOT_036,
        DOUBLE_WINDOW_SLOT_037,
        DOUBLE_WINDOW_SLOT_038,
        GRAY_DIALOG_SLOT_033,
        GRAY_DIALOG_SLOT_034,
        DOUBLE_WINDOW_SLOT_039,
        DOUBLE_WINDOW_SLOT_040,
        UNI_WINDOW_SLOT_017,
        UNI_WINDOW_SLOT_018,
        UNI_WINDOW_SLOT_019,
        UNI_WINDOW_SLOT_020,
        DOUBLE_WINDOW_SLOT_041,
        DOUBLE_WINDOW_SLOT_042,
        DOUBLE_WINDOW_SLOT_043,
        UNI_WINDOW_SLOT_021,
        UNI_WINDOW_SLOT_022,
        UNI_WINDOW_SLOT_023,
        DN_EXTRA_192,
        DN_EXTRA_193,
        DN_EXTRA_194,
        DN_EXTRA_195,
        DN_EXTRA_196,
        DN_EXTRA_197,
        DN_EXTRA_198,
        DN_EXTRA_199,
        DN_EXTRA_200,
        DN_EXTRA_201,
        DN_EXTRA_202,
        DN_EXTRA_203,
        DN_EXTRA_204,
        DN_EXTRA_205,
        DN_EXTRA_206,
        DN_EXTRA_207,
        DN_EXTRA_208,
        DN_EXTRA_209,
        DN_EXTRA_210,
        DN_EXTRA_211,
        DN_EXTRA_212,
        DN_EXTRA_213,
        DN_EXTRA_214,
        DN_EXTRA_215,
        DN_EXTRA_216,
        DN_EXTRA_217,
        DN_EXTRA_218,
        DN_EXTRA_219,
        DN_EXTRA_220,
        DN_EXTRA_221,
        DN_EXTRA_222,
        DN_EXTRA_223,
        DN_EXTRA_224,
        DN_EXTRA_225,
        DN_EXTRA_226,
        DN_EXTRA_227,
        DN_EXTRA_228;
    }


    private static final byte[] DN_CCOLOR_VALUES = new byte[] {
        (byte) 0x71,
        (byte) 0x70,
        (byte) 0x78,
        (byte) 0x74,
        (byte) 0x20,
        (byte) 0x28,
        (byte) 0x24,
        (byte) 0x17,
        (byte) 0x1F,
        (byte) 0x1A,
        (byte) 0x31,
        (byte) 0x31,
        (byte) 0x78,
        (byte) 0x7F,
        (byte) 0x1F,
        (byte) 0x31,
        (byte) 0x3F,
        (byte) 0x3A,
        (byte) 0x13,
        (byte) 0x13,
        (byte) 0x3E,
        (byte) 0x21,
        (byte) 0x3F,
        (byte) 0x70,
        (byte) 0x7F,
        (byte) 0x7A,
        (byte) 0x13,
        (byte) 0x13,
        (byte) 0x70,
        (byte) 0x7F,
        (byte) 0x7E,
        (byte) 0x70,
        (byte) 0x7F,
        (byte) 0x7A,
        (byte) 0x13,
        (byte) 0x13,
        (byte) 0x70,
        (byte) 0x70,
        (byte) 0x7F,
        (byte) 0x7E,
        (byte) 0x8F,
        (byte) 0x8B,
        (byte) 0x9F,
        (byte) 0x78,
        (byte) 0x8E,
        (byte) 0x70,
        (byte) 0x78,
        (byte) 0x7F,
        (byte) 0x7E,
        (byte) 0x0F,
        (byte) 0x9F,
        (byte) 0x0E,
        (byte) 0x9F,
        (byte) 0x79,
        (byte) 0x31,
        (byte) 0x31,
        (byte) 0x30,
        (byte) 0x0F,
        (byte) 0x3F,
        (byte) 0x31,
        (byte) 0x8F,
        (byte) 0x30,
        (byte) 0x3E,
        (byte) 0x30,
        (byte) 0x38,
        (byte) 0x3E,
        (byte) 0x0F,
        (byte) 0x07,
        (byte) 0x0E,
        (byte) 0x87,
        (byte) 0x8F,
        (byte) 0x8F,
        (byte) 0x8B,
        (byte) 0x8F,
        (byte) 0xF0,
        (byte) 0x87,
        (byte) 0x7F,
        (byte) 0x1C,
        (byte) 0x00,
        (byte) 0x87,
        (byte) 0x8F,
        (byte) 0x8B,
        (byte) 0x8F,
        (byte) 0xF0,
        (byte) 0x87,
        (byte) 0x8F,
        (byte) 0x8E,
        (byte) 0x30,
        (byte) 0x3E,
        (byte) 0x3F,
        (byte) 0x8F,
        (byte) 0x87,
        (byte) 0x70,
        (byte) 0x87,
        (byte) 0x8F,
        (byte) 0x3F,
        (byte) 0x8F,
        (byte) 0x3F,
        (byte) 0x8E,
        (byte) 0x8E,
        (byte) 0x70,
        (byte) 0x8B,
        (byte) 0x87,
        (byte) 0x30,
        (byte) 0x3F,
        (byte) 0x0F,
        (byte) 0x3E,
        (byte) 0x0E,
        (byte) 0x31,
        (byte) 0x31,
        (byte) 0x00,
        (byte) 0x87,
        (byte) 0x8F,
        (byte) 0x8B,
        (byte) 0x8F,
        (byte) 0xF0,
        (byte) 0x87,
        (byte) 0x70,
        (byte) 0x8B,
        (byte) 0x8E,
        (byte) 0x8F,
        (byte) 0x87,
        (byte) 0x8F,
        (byte) 0x87,
        (byte) 0x8F,
        (byte) 0x70,
        (byte) 0x7F,
        (byte) 0x7A,
        (byte) 0x13,
        (byte) 0x13,
        (byte) 0x70,
        (byte) 0x30,
        (byte) 0x79,
        (byte) 0x39,
        (byte) 0x7E,
        (byte) 0x7E,
        (byte) 0x7F,
        (byte) 0x70,
        (byte) 0x37,
        (byte) 0x3F,
        (byte) 0x3A,
        (byte) 0x13,
        (byte) 0x13,
        (byte) 0x30,
        (byte) 0x3E,
        (byte) 0x1E,
        (byte) 0x30,
        (byte) 0x38,
        (byte) 0x3E,
        (byte) 0x0F,
        (byte) 0x07,
        (byte) 0x0E,
        (byte) 0x87,
        (byte) 0x8F,
        (byte) 0x8F,
        (byte) 0x8B,
        (byte) 0x8F,
        (byte) 0xF0,
        (byte) 0x87,
        (byte) 0x70,
        (byte) 0x8E,
        (byte) 0x30,
        (byte) 0x3F,
        (byte) 0x83,
        (byte) 0x8E,
        (byte) 0x38,
        (byte) 0x3F,
        (byte) 0x3A,
        (byte) 0x31,
        (byte) 0x3F,
        (byte) 0x70,
        (byte) 0x8F,
        (byte) 0x8B,
        (byte) 0x8A,
        (byte) 0x83,
        (byte) 0x82,
        (byte) 0x8D,
        (byte) 0x9E,
        (byte) 0x8E,
        (byte) 0x8C,
        (byte) 0x89,
        (byte) 0x07,
        (byte) 0x7F,
        (byte) 0x03,
        (byte) 0x0F,
        (byte) 0x8F,
        (byte) 0x8F,
        (byte) 0x8E,
        (byte) 0x8F,
        (byte) 0x8D,
        (byte) 0x8B,
        (byte) 0x70,
        (byte) 0x07,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x3F,
        (byte) 0x08,
        (byte) 0xCF,
        (byte) 0xCE,
        (byte) 0x0F,
        (byte) 0x0E
    };

    private static final TPalette APP_PALETTE = buildPalette();

    private static TPalette buildPalette() {
        AppColorSlot[] slots = AppColorSlot.values();
        if (slots.length != DN_CCOLOR_VALUES.length) {
            throw new IllegalStateException("Palette slot count mismatch: slots=" + slots.length
                    + ", values=" + DN_CCOLOR_VALUES.length);
        }
        EnumMap<AppColorSlot, Byte> map = new EnumMap<>(AppColorSlot.class);
        for (int i = 0; i < slots.length; i++) {
            map.put(slots[i], DN_CCOLOR_VALUES[i]);
        }
        return new TPalette(map);
    }

    public static TPalette palette() {
        return APP_PALETTE;
    }
}
